#!/bin/bash
# yaoguais <newtopstdio@163.com>
# start all the services

/scripts/mysql/docker-entrypoint.sh \
 mysqld \
 --defaults-file=/etc/mysql/conf.d/my.cnf &

/scripts/mysql/docker-entrypoint.sh \
 mysqld \
 --defaults-file=/etc/mysql-slave/conf.d/my.cnf &

cd /var/lib/redis
/scripts/redis/docker-entrypoint.sh redis-server /etc/redis/redis.conf &

cd /var/lib/redis-slave
/scripts/redis/docker-entrypoint.sh redis-server /etc/redis-slave/redis.conf &

nginx -c /etc/nginx/nginx.conf &

php-fpm &

/scripts/mongodb/docker-entrypoint.sh mongod -f /etc/mongodb/mongod.conf &

tail -f /dev/null
