apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: lnmp-one-deployment
  namespace: lnmp-one
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lnmp-one-deployment
    spec:
      containers:
        - 
          image: mysql
          name: mysql
          env:
            - 
              name: "MYSQL_ROOT_PASSWORD"
              value: "123456"
            - 
              name: "MYSQL_DATABASE"
              value: "test"
        -
          name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
        -
          name: fpm
          image: fpm
          ports:
            - containerPort: 9000
        -
          name: nginx
          image: yaoguais/k8s-lnmp-base-nginx
          ports:
            - containerPort: 6000
        - 
          image: yaoguais/k8s-php-ping-redis-mysql
          name: php
          env: 
              - 
                name: "MYSQL_HOST"
                value: "127.0.0.1"
              - 
                name: "MYSQL_PORT"
                value: "3306"
              - 
                name: "MYSQL_USER"
                value: "root"
              - 
                name: "MYSQL_PASSWORD"
                value: "123456"
              - 
                name: "MYSQL_DATABASE"
                value: "test"
              - 
                name: "REDIS_HOST"
                value: "127.0.0.1"
              - 
                name: "REDIS_PORT"
                value: "6379"
      volumes:
        - name: redis-data
          emptyDir: {}
        - name: website-data
          emptyDir: {}

