apiVersion: v1
kind: Pod
metadata: 
  labels: 
    name: mysql
  name: mysql
  namespace: lnmp-base
spec: 
  containers: 
    - 
      image: mysql
      name: mysql
      env:
        - 
          name: "MYSQL_ROOT_PASSWORD"
          value: "123456"
        - 
          name: "MYSQL_DATABASE"
          value: "test"

