apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: lnmp-base
  labels:
    name: nginx
spec:
  containers:
  -
    name: nginx
    image: yaoguais/k8s-lnmp-base-nginx:v1
    ports:
    - containerPort: 80
    - containerPort: 6000

